repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #- id: no-commit-to-branch
      #  args:
      #    - --branch
      #    - master
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      #- id: check-docstring-first
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key
      - id: forbid-submodules

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
        args:
          - --line-length=100
          - --profile
          - black

  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3.11
      args:
        - --line-length=100
        - --skip-string-normalization

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    - id: pycln
      language_version: python3.11
      types: [python]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-gitlab-ci
        args: ["--verbose"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
